name: GH Antrea-Proxy 1.4
on:
  push:
    branches:
      - main
  pull_request:
    branches:
jobs:
  kind-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          config: hack/kind-multi-worker-nocni.yaml
          version: v0.11.0
          node_image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
      - run: |
          kubectl apply -f https://raw.githubusercontent.com/antrea-io/antrea/main/build/yamls/antrea.yml
      - run: |
          ./hack/install_metallb.sh
      - run: |
          go test -v ./tests
