name: GH KPNG - nftables
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
jobs:
  kind-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/checkout@master
        with:
          repository: kubernetes-sigs/kpng
          path: ./kpng
      - run: |
          pushd kpng/hack
            sed -i 's/^#build/build/' kpng-local-up.sh
            IMAGE=knabben/kpng:nft ./kpng-local-up.sh
          popd
          kubectl wait --for=condition=ready -n kube-system -l k8s-app=calico-node pods --timeout=60s
          ./hack/install_metallb.sh
      - run: |
          go test -v ./tests
