name: Kube-Proxy-IPTables-1.21-mode-perf-testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
jobs:
  kind-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          config: hack/kind-multi-worker.yaml
          version: v0.11.0
      - run: |
          ./hack/install_metallb.sh
      - run: |
          go install gotest.tools/gotestsum@latest
          make summary SUMMARY_OPTIONS="--labels="type=iperf""
