name: Kube-Proxy-IPTables-1.22-mode
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
jobs:
  kind-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          config: hack/kind-multi-worker.yaml
          version: v0.11.0
          node_image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
      - run: |
          ./hack/install_metallb.sh
      - run: |
          go install gotest.tools/gotestsum@latest
          go test -v ./tests --skip-labels="type=iperf"
